version: "3"

services:
  moveit:
    image: ghcr.io/peterdavidfagan/mujoco_ravens_motion_planning
    build:
      context: ../../
      dockerfile: .docker/motion_planning/Dockerfile.motion_planning
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${DOCKER_XAUTH}
    volumes:
      - /tmp/.X11-unix:/tml/.X11-unix:rw
      - ${DOCKER_XAUTH}:${DOCKER_XAUTH}
    devices:
      - "/dev:/dev"
    privileged: true
    network_mode: "host"
    command: echo "mission accomplished"
