min_objects: 1
max_objects: 10
min_object_size: 0.02
max_object_size: 0.05
sample_size: true
sample_colour: true
color_noise: 0.1
shapes:
  - cube
  - cylinder
  - rectangle
colours:
  - red
  - green
  - blue
  - yellow
  - magenta
  - cyan
  - grey
