arm:
  _target_: mujoco_ravens.models.arms.franka_emika.FER
  relative_robot_mjcf_path: "./mujoco_menagerie/franka_emika_panda/panda_nohand.xml" # relative to scripts directory
  actuator_config:
    type: "motor"
    high_torque_motor:
      ctrlrange: '-87 87'
      forcerange: '-87 87'
    low_torque_motor:
      ctrlrange: '-12 12'
      forcerange: '-12 12'
    joint_actuator_mapping:
      joint1: "high_torque_motor"
      joint2: "high_torque_motor"
      joint3: "high_torque_motor"
      joint4: "high_torque_motor"
      joint5: "low_torque_motor"
      joint6: "low_torque_motor"
      joint7: "low_torque_motor"


gripper:
  _target_: dm_robotics.moma.models.end_effectors.robot_hands.robotiq_2f85.Robotiq2F85
